# Generated by Django 5.1 on 2024-09-06 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="date_posted",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="date_updated",
            new_name="updated_at",
        ),
    ]
